version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./doc_root/public:/var/www/zf-sample/public

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME:-zf_sample}
      MYSQL_USER: ${DB_USER:-db_user}
      MYSQL_PASSWORD: ${DB_PASS:-secret}
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./doc_root:/var/www/zf-sample

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME:-zf_sample}
      MYSQL_USER: ${DB_USER:-db_user}
      MYSQL_PASSWORD: ${DB_PASS:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-secret}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
