<?php
$title = '商品の編集';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// 要素にデフォルトの CSS クラスとプレースホルダーテキストを提供する。
$itemName = $form->get('item_name');
$itemName->setAttribute('class', 'form-control');
$itemName->setAttribute('placeholder', '商品名');

$price = $form->get('price');
$price->setAttribute('class', 'form-control');
$price->setAttribute('placeholder', '商品単価');

// 送信ボタン用の CSS クラスを提供する。
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('product', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<!-- フォームグループの div で要素をラップし、その中でラベル、要素、エラーを別々にレンダリングする。 -->
<div class="form-group">
    <?= $this->formLabel($itemName) ?>
    <?= $this->formElement($itemName) ?>
    <span class="text-danger"><?= $this->formElementErrors()->render($itemName, ['class' => 'help-block']) ?></span>
</div>

<div class="form-group">
    <?= $this->formLabel($price) ?>
    <?= $this->formElement($price) ?>
    <span class="text-danger"><?= $this->formElementErrors()->render($price, ['class' => 'help-block']) ?></span>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
